# Generated by Django 3.2.8 on 2021-10-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0005_auto_20211025_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
