# Generated by Django 3.2.8 on 2021-10-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0008_auto_20211027_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='obj_id',
        ),
    ]
