# Generated by Django 3.2.8 on 2021-10-28 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0010_auto_20211028_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='score',
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
